services:
    mysql:
        image: mysql:8.4
        container_name: 62595_mysql
        ports:
          - "3307:3306"
          - "33061:33060"
        volumes:
          - mysql-data:/var/lib/mysql
        environment:
          - MYSQL_ROOT_HOST=%
          - MYSQL_ROOT_PASSWORD=pass
          - MYSQL_DATABASE=fsd
          - MYSQL_USER=user
          - MYSQL_PASSWORD=pass
volumes:
    mysql-data: